@startuml

!define C4Container https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include C4Container

skinparam svgLinkTarget foo

System_Boundary(c1, "edx-platform: edx-staging", $link="https://github.com/eol-uchile/edx-staging") {
    System_Boundary(c2, "requirements", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/") {
        
            System_Boundary(apis, "apis", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/apis.txt") {
            
                Container(apis1, "portal_api", $link="https://github.com/eol-uchile/portal_api/releases/tag/0.3")
            
            }
        
            System_Boundary(apps, "apps", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/apps.txt") {
            
                Container(apps1, "course_classification", $link="https://github.com/eol-uchile/course_classification/releases/tag/1.3.0-dev2")
            
                Container(apps2, "eol_duplicate_xblock", $link="https://github.com/eol-uchile/eol_duplicate_xblock/releases/tag/1.0.0")
            
                Container(apps3, "eol_sso_login", $link="https://github.com/eol-uchile/eol_sso_login/releases/tag/0.1.1")
            
                Container(apps4, "eol_survey", $link="https://github.com/eol-uchile/eol_survey/releases/tag/1.0.0")
            
                Container(apps5, "eol_vimeo", $link="https://github.com/eol-uchile/eol_vimeo/releases/tag/1.0.1")
            
                Container(apps6, "edx-proctoring", $link="https://github.com/openedx/edx-proctoring/releases/tag/2.6.7")
            
                Container(apps7, "eol_contact_form", $link="https://github.com/eol-uchile/eol_contact_form/releases/tag/0.5.2")
            
            }
        
            System_Boundary(python_packages, "python_packages", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/python_packages.txt") {
            
                Container(python_packages1, "django-redis")
            
                Container(python_packages2, "edx-username-changer", $link="https://github.com/mitodl/edx-username-changer.git/releases/tag/main")
            
                Container(python_packages3, "fluent-logger")
            
                Container(python_packages4, "python-json-logger")
            
            }
        
            System_Boundary(reports, "reports", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/reports.txt") {
            
                Container(reports1, "eol_report_analytics", $link="https://github.com/eol-uchile/eol_report_analytics/releases/tag/0.0.1")
            
            }
        
            System_Boundary(tabs_plugins, "tabs_plugins", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/tabs_plugins.txt") {
            
                Container(tabs_plugins1, "eol_completion", $link="https://github.com/eol-uchile/eol_completion/releases/tag/0.0.1+open")
            
                Container(tabs_plugins2, "eol_course_email", $link="https://github.com/eol-uchile/eol_course_email/commit/cfcca8a18389f64a1383f686a684c585019d16f1")
            
                Container(tabs_plugins3, "eol_progress_tab", $link="https://github.com/eol-uchile/eol_progress_tab/commit/698177942488d4bc3c3b931887e6fef0b94473aa")
            
                Container(tabs_plugins4, "welcome-mail", $link="https://github.com/eol-uchile/eol_welcome_mail/releases/tag/0.0.1")
            
            }
        
            System_Boundary(xblocks, "xblocks", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/xblocks.txt") {
            
                Container(xblocks1, "corfogeneratecode", $link="https://github.com/eol-uchile/corfo_generate_code/commit/a6b171148ba7278c05c664f0eb41f52743634bd2")
            
                Container(xblocks2, "ora2", $link="https://github.com/eol-uchile/edx-ora2/commit/e873498bd2671b830f19a2441ec1608b7d4bbbc4")
            
                Container(xblocks3, "edx-sga", $link="https://github.com/eol-uchile/edx-sga/releases/tag/0.10.0+eol3.1.2-dev1")
            
                Container(xblocks4, "scormxblock-xblock", $link="https://github.com/eol-uchile/edx_xblock_scorm/commit/c23184c0e22a7847f0b0c917bbe431c2973770fb")
            
                Container(xblocks5, "eolcontainer-xblock", $link="https://github.com/eol-uchile/eol-container-xblock/releases/tag/v1.0.0")
            
                Container(xblocks6, "eolcourseprogram-xblock", $link="https://github.com/eol-uchile/eol-course-program-xblock/releases/tag/0.1.1")
            
                Container(xblocks7, "eol_forum_notifications", $link="https://github.com/eol-uchile/eol_forum_notifications/releases/tag/1.0.0")
            
                Container(xblocks8, "eolgradediscussion", $link="https://github.com/eol-uchile/eol_gradeforum_xblock/releases/tag/1.0.0")
            
                Container(xblocks9, "eollistgrade-xblock", $link="https://github.com/eol-uchile/eol_list_grade/releases/tag/1.0.0")
            
                Container(xblocks10, "eoldiscussion-xblock", $link="https://github.com/eol-uchile/eol_xblock_discussion/releases/tag/1.0.1")
            
                Container(xblocks11, "eolzoom-xblock", $link="https://github.com/eol-uchile/eol-zoom-xblock/releases/tag/1.1.2")
            
                Container(xblocks12, "ubcpi-xblock", $link="https://github.com/eol-uchile/ubcpi/releases/tag/1.0.0")
            
                Container(xblocks13, "pdf-xblock", $link="https://github.com/eol-uchile/pdfXBlock/releases/tag/v0.5.1")
            
            }
        
    }

    System_Boundary(theme, "Themes", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/themes/") {
        
            Container(theme1, "open-uchile-theme", $link="https://github.com/eol-uchile/open-uchile-theme.git")
        
    }

    System_Boundary(dockerfile, "edx-platform base", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/Dockerfile") {
            Container(dk, "testing-ou-koa", $link="https://ghcr.io/eol-uchile/edx-platform:testing-ou-koa")
    }
}

SHOW_LEGEND()

@enduml