@startuml

!define C4Container https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include C4Container

skinparam svgLinkTarget foo

System_Boundary(c1, "edx-platform: edx-staging", $link="https://github.com/eol-uchile/edx-staging") {
    System_Boundary(c2, "requirements", $link="https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/") {
        
            System_Boundary(apis, "apis", $link="https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/apis.txt") {
            
                Container(apis1, "CMM-API", $link="https://github.com/eol-uchile/CMM-API")
            
                Container(apis2, "norteamericano-api", $link="https://github.com/eol-virtuallabx/norteamericano-api")
            
                Container(apis3, "portal_api", $link="https://github.com/eol-uchile/portal_api")
            
            }
        
            System_Boundary(apps, "apps", $link="https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/apps.txt") {
            
                Container(apps1, "eol_auto_login", $link="https://github.com/eol-uchile/eol_auto_login")
            
                Container(apps2, "eol_contact_form", $link="https://github.com/eol-uchile/eol_contact_form")
            
                Container(apps3, "course_classification", $link="https://github.com/eol-uchile/course_classification")
            
                Container(apps4, "norteamericano_custom_form", $link="https://github.com/eol-virtuallabx/norteamericano_custom_form")
            
                Container(apps5, "eol_duplicate_xblock", $link="https://github.com/eol-uchile/eol_duplicate_xblock")
            
                Container(apps6, "eol_jump_to", $link="https://github.com/eol-uchile/eol_jump_to")
            
                Container(apps7, "edx-newsletters", $link="https://github.com/eol-uchile/edx-newsletters")
            
                Container(apps8, "edx-proctoring", $link="https://github.com/eol-uchile/edx-proctoring")
            
                Container(apps9, "redfid_logout", $link="https://github.com/eol-uchile/redfid_logout")
            
                Container(apps10, "edx-search", $link="https://github.com/eol-uchile/edx-search")
            
                Container(apps11, "eol_sso_login", $link="https://github.com/eol-uchile/eol_sso_login.git")
            
                Container(apps12, "super_csv", $link="https://github.com/eol-uchile/super-csv.git")
            
                Container(apps13, "uchileedxlogin", $link="https://github.com/eol-uchile/uchileedxlogin")
            
                Container(apps14, "edx-ucursos", $link="https://github.com/eol-uchile/edx-ucursos")
            
                Container(apps15, "edx-userdata", $link="https://github.com/eol-uchile/edx-userdata")
            
                Container(apps16, "eol_vimeo", $link="https://github.com/eol-uchile/eol_vimeo")
            
            }
        
            System_Boundary(python_packages, "python_packages", $link="https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/python_packages.txt") {
            
                Container(python_packages1, "django-debug-toolbar")
            
                Container(python_packages2, "django-redis")
            
                Container(python_packages3, "fluent-logger")
            
                Container(python_packages4, "python-json-logger")
            
                Container(python_packages5, "setuptools")
            
            }
        
            System_Boundary(reports, "reports", $link="https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/reports.txt") {
            
                Container(reports1, "eol_grade_ucursos", $link="https://github.com/eol-uchile/eol_grade_ucursos")
            
                Container(reports2, "eol_report_analytics", $link="https://github.com/eol-uchile/eol_report_analytics")
            
                Container(reports3, "eol_report_certificate", $link="https://github.com/eol-uchile/eol_report_certificate")
            
                Container(reports4, "eol_xblock_completion", $link="https://github.com/eol-uchile/eol_xblock_completion")
            
            }
        
            System_Boundary(tabs_plugins, "tabs_plugins", $link="https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/tabs_plugins.txt") {
            
                Container(tabs_plugins1, "eol_completion", $link="https://github.com/eol-uchile/eol_completion")
            
                Container(tabs_plugins2, "eol_course_email", $link="https://github.com/eol-uchile/eol_course_email")
            
                Container(tabs_plugins3, "eol_feedback", $link="https://github.com/eol-uchile/eol_feedback")
            
                Container(tabs_plugins4, "eol_progress_tab", $link="https://github.com/eol-uchile/eol_progress_tab")
            
                Container(tabs_plugins5, "welcome_mail", $link="https://github.com/eol-uchile/eol_welcome_mail")
            
            }
        
            System_Boundary(xblocks, "xblocks", $link="https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/xblocks.txt") {
            
                Container(xblocks1, "eolconditional-xblock", $link="https://github.com/eol-uchile/eol-conditional-xblock.git")
            
                Container(xblocks2, "eolcontainer-xblock", $link="https://github.com/eol-uchile/eol-container-xblock.git")
            
                Container(xblocks3, "corfo_generate_code", $link="https://github.com/eol-uchile/corfo_generate_code")
            
                Container(xblocks4, "eolcourseprogram-xblock", $link="https://github.com/eol-uchile/eol-course-program-xblock")
            
                Container(xblocks5, "eoldialogs-xblock", $link="https://github.com/eol-uchile/eol-dialogs-xblock.git")
            
                Container(xblocks6, "dialogsquestionsxblock-xblock", $link="https://github.com/eol-uchile/eol-dialogs-question-xblock")
            
                Container(xblocks7, "eoldiscussion", $link="https://github.com/eol-uchile/eol_xblock_discussion")
            
                Container(xblocks8, "xblock-drag-and-drop-v2", $link="https://github.com/eol-uchile/xblock-drag-and-drop-v2")
            
                Container(xblocks9, "xblock-eoc-journal", $link="https://github.com/eol-uchile/xblock-eoc-journal")
            
                Container(xblocks10, "flow-control-xblock", $link="https://github.com/eol-uchile/flow-control-xblock")
            
                Container(xblocks11, "eol_forum_notifications", $link="https://github.com/eol-uchile/eol_forum_notifications")
            
                Container(xblocks12, "free-text-response", $link="https://github.com/eol-uchile/free-text-response")
            
                Container(xblocks13, "generate_certificate_xblock", $link="https://github.com/eol-uchile/generate_certificate_xblock")
            
                Container(xblocks14, "eol_gradeforum_xblock", $link="https://github.com/eol-uchile/eol_gradeforum_xblock")
            
                Container(xblocks15, "eol_img_annotation", $link="https://github.com/eol-uchile/eol_img_annotation")
            
                Container(xblocks16, "xblock_in_video_quiz", $link="https://github.com/eol-uchile/xblock-in-video-quiz")
            
                Container(xblocks17, "eol_list_grade", $link="https://github.com/eol-uchile/eol_list_grade")
            
                Container(xblocks18, "lti-consumer-xblock", $link="https://github.com/eol-uchile/xblock-lti-consumer")
            
                Container(xblocks19, "ora2", $link="https://github.com/eol-uchile/edx-ora2.git")
            
                Container(xblocks20, "payment_link_xblock", $link="https://github.com/eol-uchile/payment_link_xblock")
            
                Container(xblocks21, "pdf-xblock", $link="https://github.com/eol-uchile/pdfXBlock")
            
                Container(xblocks22, "eolpersistenttab-xblock", $link="https://github.com/eol-uchile/eol-persistent-tab-xblock")
            
                Container(xblocks23, "problem-builder", $link="https://github.com/eol-uchile/problem-builder")
            
                Container(xblocks24, "proctoring_hide_xblock", $link="https://github.com/eol-uchile/proctoring_hide_xblock")
            
                Container(xblocks25, "eolquestion-xblock", $link="https://github.com/eol-uchile/eol-question-xblock.git")
            
                Container(xblocks26, "scormxblock", $link="https://github.com/eol-uchile/edx_xblock_scorm")
            
                Container(xblocks27, "sence-xblock", $link="https://github.com/eol-uchile/sence-xblock")
            
                Container(xblocks28, "edx-sga", $link="https://github.com/eol-uchile/edx-sga")
            
                Container(xblocks29, "ubcpi", $link="https://github.com/eol-uchile/ubcpi")
            
                Container(xblocks30, "vof-xblock", $link="https://github.com/eol-uchile/eol-vof-xblock.git")
            
                Container(xblocks31, "eolzoom-xblock", $link="https://github.com/eol-uchile/eol-zoom-xblock")
            
            }
        
    }

    System_Boundary(theme, "Themes", $link="https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/themes/") {
        
            Container(theme1, "alpha-project-theme", $link="https://github.com/eol-uchile/alpha-project-theme.git")
        
            Container(theme2, "cmm-openedx", $link="https://github.com/eol-uchile/cmm-openedx")
        
            Container(theme3, "eduonline-ing", $link="https://github.com/eol-uchile/eol_eduonline_ing_theme")
        
            Container(theme4, "edx-uabierta", $link="https://github.com/eol-uchile/uabierta-theme")
        
            Container(theme5, "eol-uchile-2020", $link="https://github.com/eol-uchile/eol-uchile-theme-2020")
        
            Container(theme6, "norteamericano-theme", $link="https://github.com/eol-virtuallabx/norteamericano-theme.git")
        
            Container(theme7, "open-uchile-theme", $link="https://github.com/open-uchile/open-uchile-theme.git")
        
            Container(theme8, "redfid-theme", $link="https://github.com/eol-uchile/redfid-theme.git")
        
            Container(theme9, "virtual-labx-cla-theme", $link="https://github.com/eol-virtuallabx/virtual-labx-cla-theme.git")
        
            Container(theme10, "virtual-labx-theme", $link="https://github.com/eol-uchile/virtual-labx-theme.git")
        
    }

    System_Boundary(dockerfile, "edx-platform base", $link="https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/Dockerfile") {
            Container(dk, "testing-koa", $link="https://ghcr.io/eol-uchile/edx-platform:testing-koa")
    }
}

SHOW_LEGEND()

@enduml