@startuml

!define C4Container https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include C4Container

skinparam svgLinkTarget foo

System_Boundary(c1, "edx-platform: edx-staging", $link="https://github.com/eol-uchile/edx-staging") {
    System_Boundary(c2, "requirements", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/") {
        
            System_Boundary(apis, "apis", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/apis.txt") {
            
                Container(apis1, "portal_api", $link="https://github.com/open-uchile/portal_api")
            
            }
        
            System_Boundary(apps, "apps", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/apps.txt") {
            
                Container(apps1, "eol_auto_login", $link="https://github.com/eol-uchile/eol_auto_login")
            
                Container(apps2, "eol_contact_form", $link="https://github.com/open-uchile/eol_contact_form")
            
                Container(apps3, "course_classification", $link="https://github.com/eol-uchile/course_classification")
            
                Container(apps4, "eol_duplicate_xblock", $link="https://github.com/eol-uchile/eol_duplicate_xblock")
            
                Container(apps5, "edx-proctoring", $link="https://github.com/open-uchile/edx-proctoring")
            
                Container(apps6, "edx-search", $link="https://github.com/eol-uchile/edx-search")
            
                Container(apps7, "eol_sso_login", $link="https://github.com/eol-uchile/eol_sso_login")
            
                Container(apps8, "eol_survey", $link="https://github.com/eol-uchile/eol_survey")
            
                Container(apps9, "eol_vimeo", $link="https://github.com/eol-uchile/eol_vimeo")
            
            }
        
            System_Boundary(python_packages, "python_packages", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/python_packages.txt") {
            
                Container(python_packages1, "django-redis")
            
                Container(python_packages2, "fluent-logger")
            
                Container(python_packages3, "python-json-logger")
            
            }
        
            System_Boundary(reports, "reports", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/reports.txt") {
            
                Container(reports1, "eol_report_analytics", $link="https://github.com/eol-uchile/eol_report_analytics")
            
            }
        
            System_Boundary(tabs_plugins, "tabs_plugins", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/tabs_plugins.txt") {
            
                Container(tabs_plugins1, "eol_completion", $link="https://github.com/eol-uchile/eol_completion")
            
                Container(tabs_plugins2, "eol_progress_tab", $link="https://github.com/eol-uchile/eol_progress_tab")
            
                Container(tabs_plugins3, "welcome-mail", $link="https://github.com/eol-uchile/eol_welcome_mail")
            
            }
        
            System_Boundary(xblocks, "xblocks", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/requirements/xblocks.txt") {
            
                Container(xblocks1, "eolcontainer-xblock", $link="https://github.com/eol-uchile/eol-container-xblock.git")
            
                Container(xblocks2, "corfogeneratecode", $link="https://github.com/eol-uchile/corfo_generate_code")
            
                Container(xblocks3, "eolcourseprogram-xblock", $link="https://github.com/eol-uchile/eol-course-program-xblock")
            
                Container(xblocks4, "eoldiscussion-xblock", $link="https://github.com/eol-uchile/eol_xblock_discussion")
            
                Container(xblocks5, "eol_forum_notifications", $link="https://github.com/eol-uchile/eol_forum_notifications")
            
                Container(xblocks6, "eolgradediscussion", $link="https://github.com/eol-uchile/eol_gradeforum_xblock")
            
                Container(xblocks7, "eollistgrade-xblock", $link="https://github.com/eol-uchile/eol_list_grade")
            
                Container(xblocks8, "ora2", $link="https://github.com/eol-uchile/edx-ora2.git")
            
                Container(xblocks9, "pdf-xblock", $link="https://github.com/open-uchile/pdfXBlock")
            
                Container(xblocks10, "scormxblock-xblock", $link="https://github.com/eol-uchile/edx_xblock_scorm")
            
                Container(xblocks11, "edx-sga", $link="https://github.com/eol-uchile/edx-sga")
            
                Container(xblocks12, "ubcpi-xblock", $link="https://github.com/eol-uchile/ubcpi")
            
                Container(xblocks13, "eolzoom-xblock", $link="https://github.com/eol-uchile/eol-zoom-xblock")
            
            }
        
    }

    System_Boundary(theme, "Themes", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/themes/") {
        
            Container(theme1, "open-uchile-theme", $link="https://github.com/open-uchile/open-uchile-theme.git")
        
    }

    System_Boundary(dockerfile, "edx-platform base", $link="https://github.com/eol-uchile/edx-staging/blob/openuchile-release/koa/Dockerfile") {
            Container(dk, "testing-ou-koa", $link="https://ghcr.io/eol-uchile/edx-platform:testing-ou-koa")
    }
}

SHOW_LEGEND()

@enduml