name: Generate Diagram
on:
  push:
    branches:
      - 'eol-release/koa'
    paths:
      - 'Dockerfile'
      - 'requirements/**.txt'
      - '.github/workflows/diagram.yml'
      - 'templates/diagram_template.j2'
      - 'themes/**'
      - '.gitmodules'
      - 'gen_deps_diagram.py'

# Required for the workflow to be reused by other repositories.
  workflow_call:
    secrets:
      SECRET_DIAGRAM:
        required: true

jobs:
  generate_diagram:
    runs-on: ubuntu-latest
    name: PlantUML Diagram

    steps:

    - name: Verify token
      run: git ls-remote --tags --heads https://$SECRET_DIAGRAM@github.com/${{ github.repository }} HEAD

    - name: Checkout
      run: |
        git clone --single-branch --depth 1 https://github.com/${{ github.repository }} .
        git submodule update --init --recursive
      env:
        TOKEN: ${{ secrets.SECRET_DIAGRAM }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Jinja2==3.0.3
      shell: bash

    - name: Create templates directory
      run: test -d templates || mkdir templates

    - name: Download template
      run: wget https://github.com/eol-uchile/edx-staging/raw/eol-release/koa/templates/diagram_template.j2 -O templates/diagram_template.j2

    - name: Download diagram generator script
      run: wget https://github.com/eol-uchile/edx-staging/raw/eol-release/koa/gen_deps_diagram.py -O gen_deps_diagram.py

    - name: Generate diagram.puml
      run: python gen_deps_diagram.py

    - name: Draw diagram
      uses: Timmy/plantuml-action@v1
      with:
        args: '-tsvg diagrams/diagram.puml'

    - name: Configure Git
      run: |
        git config --global user.name "eolito"
        git config --global user.email 'eol-uchile@users.noreply.github.com'

    - name: Commit UML Images
      run: |
        if [ "$(git status --porcelain)" != "" ]
        then
          git add diagrams/**
          git commit -m "Auto-generate UML diagram"
          git push origin HEAD:${{ github.ref }}
        else
          echo "No changes to commit. Skipping commit step."
        fi
