name: generate plantuml
on:
  push:
    branches:
      - 'markdown-diagram-updates'
    paths:
      - 'Dockerfile'
      - 'requirements/private.txt'
      - '.github/workflows/diagram.yml'
      - 'diagrams/diagram.puml'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: diagrams
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
