name: Docker Image CI

on:
  push:
    branches:
      - staging
      - trying

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Build Open edX
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/edx-staging:${GITHUB_SHA} --tag ghcr.io/eol-uchile/edx-staging:koa --target base

      - name: Build Static files for OpenedX S3
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/edx-staging:s3-static-${GITHUB_SHA} --tag ghcr.io/eol-uchile/edx-staging:s3-static-koa --target s3

      - name: Push
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
          echo "${CR_PAT}" | docker login ghcr.io -u eolito --password-stdin
          docker push ghcr.io/eol-uchile/edx-staging:${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/edx-staging:koa
          docker push ghcr.io/eol-uchile/edx-staging:s3-static-${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/edx-staging:s3-static-koa
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
