name: Update Image

on:
  repository_dispatch:
    types: [update-image]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.event.client_payload.project }}-release/${{ github.event.client_payload.version }}'

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Set current date as env variable
        run: echo "TS=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Open edX
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/edx-staging:${{ github.event.client_payload.code }}-${{ github.event.client_payload.version }} --tag ghcr.io/eol-uchile/edx-staging:${{ github.event.client_payload.code }}-${{ github.event.client_payload.version }}-${{ env.TS }} --target base

      - name: Build Static files for OpenedX S3
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/edx-staging:s3-static-${{ github.event.client_payload.code }}-${{ github.event.client_payload.version }} --tag ghcr.io/eol-uchile/edx-staging:s3-static-${{ github.event.client_payload.code }}-${{ github.event.client_payload.version }}-${{ env.TS }} --target s3

      - name: Login to GitHub Container Registry
        if: github.ref == format('refs/heads/{0}-release/{1}', ${{ github.event.client_payload.project }}, ${{ github.event.client_payload.version }})
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        if: github.ref == format('refs/heads/{0}-release/{1}', ${{ github.event.client_payload.project }}, ${{ github.event.client_payload.version }})
        run: |
          docker push ghcr.io/eol-uchile/edx-staging:${{ github.event.client_payload.code }}-${{ github.event.client_payload.version }}
          docker push ghcr.io/eol-uchile/edx-staging:${{ github.event.client_payload.code }}-${{ github.event.client_payload.version }}-${{ env.TS }}
          docker push ghcr.io/eol-uchile/edx-staging:s3-static-${{ github.event.client_payload.code }}-${{ github.event.client_payload.version }}
          docker push ghcr.io/eol-uchile/edx-staging:s3-static-${{ github.event.client_payload.code }}-${{ github.event.client_payload.version }}-${{ env.TS }}

  webhook:
    needs: [ build ]
    uses: ./.github/workflows/webhook.yml
    with:
      code: ${{ github.event.client_payload.code }}
    secrets: inherit
