name: Webhook Update staging

on:
  workflow_call:
    inputs:
      code:
        required: true
        type: string
  repository_dispatch:
    types: [debug-webhook]

jobs:
  webhook:
    runs-on: ubuntu-latest
    if: inputs.code || github.event.client_payload.debug
    steps:
      - name: Trigger edx-kustomize repository workflow
        run: |
          if [ "${{ inputs.code }}" == "eol" || "${{ github.event.client_payload.debug }}" == "eol" ]
          then
            curl --fail-with-body -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-uchile/edx-kustomize/dispatches --data '{"event_type": "update-images-v2", "client_payload": {"flavour": "staging"}}'
          elif [ "${{ inputs.code }}" == "ou" || "${{ github.event.client_payload.debug }}" == "ou" ]
          then
            curl --fail-with-body -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-uchile/edx-kustomize/dispatches --data '{"event_type": "update-images-v2", "client_payload": {"flavour": "ou-staging"}}'
          fi
